spring.application.name=ExamenMocMCG
server.port = 8091

spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.url=jdbc:mysql://localhost:3305/apirestexamen
spring.datasource.username=root
spring.datasource.password=albedo
spring.jpa.proper?es.hibernate.dialect=org.hibernate.dialect.MySQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.proper?es.hibernate.format_sql=true